(()=>{
'use strict';
const VERSION='0.8.0',KEY='cats-tower-v080',LEGACY_KEY='cats-tower-v01';
const ART={title:'/assets/v080/title-live-v080.webp',food:'/assets/v080/room-food-v080.webp',foodNight:'/assets/v080/room-food-night-v080.webp',home:'/assets/v080/room-home-v080.webp',lobby:'/assets/v080/room-lobby-v080.webp',roof:'/assets/v080/room-roof-v080.webp',memory:'/assets/v080/memory-first-home-v080.webp',mugi:'/assets/v080/mugi-v080.webp',mugiSleep:'/assets/v080/mugi-sleep-v080.webp',luna:'/assets/illustrations/cat-luna.v070.webp',toto:'/assets/illustrations/cat-toto.v070.webp',mimi:'/assets/illustrations/cat-mimi.v070.webp'};
const CATS={mugi:{name:'ムギ',role:'さかな食堂の店主見習い',trait:'食いしん坊。魚の匂いに誰より早く気づく。',art:ART.mugi},luna:{name:'ルナ',role:'静かな場所を探している猫',trait:'眠ることと毛糸の上で丸くなることが好き。',art:ART.luna},toto:{name:'トト',role:'見回りが得意な猫',trait:'仲間の変化にすぐ気づく、しっかり者。',art:ART.toto},mimi:{name:'ミミ',role:'箱と工作が好きな猫',trait:'新しい道具を見ると試さずにはいられない。',art:ART.mimi}};
const $=s=>document.querySelector(s),now=()=>Date.now(),clamp=(n,a,b)=>Math.min(b,Math.max(a,n)),fmt=n=>Math.max(0,Math.floor(Number(n)||0)).toLocaleString('ja-JP'),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const els={splash:$('#splash'),start:$('#startBtn'),game:$('#game'),coins:$('#coins'),income:$('#incomeText'),context:$('#contextBar'),contextIcon:$('#contextIcon'),contextText:$('#contextText'),tower:$('#tower'),scroll:$('#towerScroll'),world:document.querySelector('.world'),overview:$('#overviewBtn'),nav:$('#bottomNav'),modal:$('#modal'),tpl:$('#sheetTemplate'),toasts:$('#toastArea'),memoryBadge:$('#memoryBadge'),menu:$('#menuBtn'),coin:$('#coinBtn'),brand:$('#brandBtn')};
function fresh(){const t=now();return{version:VERSION,coins:108,stock:4,sales:0,mugiMood:82,specialization:null,autoOrder:true,orderEnds:0,homeRestored:true,firstNightDone:false,nightAttempts:0,memories:['arrival'],memoryNew:true,lastSeen:t,lastSale:t+3500,lastSupport:t,lastPet:0,lastRest:0,hasPlayed:false,sound:true}}
function migrateLegacy(raw){const s=fresh();try{const old=JSON.parse(raw);if(Number.isFinite(+old.coins))s.coins=clamp(+old.coins,0,999999);if(Number.isFinite(+old.sales))s.sales=Math.max(0,+old.sales);const food=Array.isArray(old.floors)?old.floors.find(f=>f?.type==='food'):null;if(food){s.stock=clamp(+food.stock||0,0,12);s.orderEnds=+food.orderEnd||0}s.hasPlayed=true}catch{}return s}
function normal(s){s.version=VERSION;s.coins=clamp(+s.coins||0,0,9999999);s.stock=clamp(+s.stock||0,0,12);s.sales=Math.max(0,+s.sales||0);s.mugiMood=clamp(+s.mugiMood||80,0,100);s.memories=Array.isArray(s.memories)?[...new Set(s.memories)]:['arrival'];s.lastSeen=Number.isFinite(+s.lastSeen)?+s.lastSeen:now();s.lastSale=Number.isFinite(+s.lastSale)?+s.lastSale:now()+3500;s.lastSupport=Number.isFinite(+s.lastSupport)?+s.lastSupport:now();return s}
function load(){try{const raw=localStorage.getItem(KEY);if(raw)return normal({...fresh(),...JSON.parse(raw)});const old=localStorage.getItem(LEGACY_KEY);return old?migrateLegacy(old):fresh()}catch{return fresh()}}
let state=load(),overview=false,timer=0,battle=null;
function save(){state.lastSeen=now();localStorage.setItem(KEY,JSON.stringify(state))}
function saleInterval(){return state.specialization==='street'?3300:state.specialization==='bistro'?5600:4300}function salePrice(){return state.specialization==='street'?11:state.specialization==='bistro'?22:14}function orderCost(){return state.specialization==='bistro'?38:30}
function offlineProgress(){const t=now(),seconds=Math.min(8*3600,Math.max(0,Math.floor((t-state.lastSeen)/1000)));if(seconds<8)return null;const sold=Math.min(state.stock,Math.floor(seconds/(saleInterval()/1000)));if(sold){state.stock-=sold;state.sales+=sold;state.coins+=sold*salePrice();state.mugiMood=clamp(state.mugiMood-sold*.3,0,100)}if(state.orderEnds&&state.orderEnds<=t){state.orderEnds=0;state.stock=clamp(state.stock+6,0,12)}if(!state.stock&&state.coins<35)state.coins=Math.min(35,state.coins+Math.min(seconds,35-state.coins));state.lastSeen=t;state.lastSale=t+saleInterval();save();return{seconds,sold}}
const offline=offlineProgress();
function toast(text,tone=''){const x=document.createElement('div');x.className=`toast ${tone}`;x.textContent=text;els.toasts.appendChild(x);setTimeout(()=>x.remove(),2900)}
function addMemory(id){if(!state.memories.includes(id)){state.memories.push(id);state.memoryNew=true;els.memoryBadge.classList.remove('hidden');save();toast('新しい思い出が増えました。','good')}}
function updateHeader(){els.coins.textContent=fmt(state.coins);if(state.orderEnds>now())els.income.textContent=`仕入れ ${Math.ceil((state.orderEnds-now())/1000)}秒`;else if(!state.stock&&state.coins<35)els.income.textContent='+1 / 秒 支援';else els.income.textContent=`自動営業 ${salePrice()}¢`;els.memoryBadge.classList.toggle('hidden',!state.memoryNew)}
function currentTask(){if(state.orderEnds>now())return{icon:'□',text:`商品が届くまで ${Math.ceil((state.orderEnds-now())/1000)}秒`,action:'food'};if(state.orderEnds&&state.orderEnds<=now())return{icon:'□',text:'さかな食堂に商品が届きました',action:'food'};if(!state.specialization)return{icon:'◇',text:'さかな食堂の進む方向を決める',action:'build'};if(state.stock<=2)return{icon:'≈',text:'ムギと魚を棚へ並べる',action:'food'};if(!state.firstNightDone&&state.sales>=2)return{icon:'!',text:'最初の夜番を始める',action:'lobby'};if(state.mugiMood<55)return{icon:'●',text:'共同部屋でムギを休ませる',action:'home'};return{icon:'◎',text:'ムギの今日の様子を見る',action:'home'}}
function updateContext(){const t=currentTask();els.contextIcon.textContent=t.icon;els.contextText.textContent=t.text;els.context.dataset.action=t.action}
function floorCard({type,no,name,icon,art,status,statusColor,actionLabel,actionIcon}){return`<article class="floor ${type}" data-room="${type}"><img class="roomArt" src="${art}" alt="${esc(name)}" draggable="false"><div class="floorTag"><span class="floorNo">${no}</span><span class="roomName"><i>${icon}</i>${esc(name)}</span></div><span class="roomStatus" style="--status:${statusColor}"><i></i>${status}</span>${actionLabel?`<button class="roomAction" data-action="open-room" data-room="${type}"><strong>${actionIcon}</strong>${actionLabel}</button>`:''}</article>`}
function renderTower(preserve=true){const pos=preserve?els.scroll.scrollTop:0,foodStatus=state.orderEnds>now()?`仕入れ中 · ${Math.ceil((state.orderEnds-now())/1000)}秒`:state.stock?`焼きさかなを販売中 · 在庫 ${state.stock}/12`:'魚の棚が空になっています',nightStatus=state.firstNightDone?'C.L.E.A.N.の初回監査を退けました':state.sales>=2?'最初の夜番を始められます':'店を動かすと夜番が開きます';els.tower.innerHTML=[floorCard({type:'roof',no:'ROOF',name:'猫たちの屋上',icon:'✦',art:ART.roof,status:'月と街を眺める静かな場所',statusColor:'#64cbbf',actionLabel:'全体を見る',actionIcon:'▦'}),floorCard({type:'food',no:'3F',name:'さかな食堂',icon:'≈',art:ART.food,status:foodStatus,statusColor:state.stock?'#d8ef78':'#ff815e',actionLabel:'店を見る',actionIcon:'≈'}),floorCard({type:'home',no:'2F',name:'猫の共同部屋',icon:'●',art:ART.home,status:`ムギのごきげん ${Math.round(state.mugiMood)}%`,statusColor:'#ef9c8f',actionLabel:'会いに行く',actionIcon:'●'}),floorCard({type:'lobby',no:'1F',name:'タワーロビー',icon:'⌂',art:ART.lobby,status:nightStatus,statusColor:state.sales>=2?'#ff815e':'#45d6cc',actionLabel:state.sales>=2?'夜番':'ロビー',actionIcon:state.sales>=2?'!':'⌂'})].join('');if(preserve)els.scroll.scrollTop=pos}
function render(preserve=true){updateHeader();updateContext();renderTower(preserve)}
function openSheet(title,eyebrow,html){closeSheet(false);const frag=els.tpl.content.cloneNode(true);frag.querySelector('header small').textContent=eyebrow;frag.querySelector('h2').textContent=title;frag.querySelector('.sheetBody').innerHTML=html;els.modal.appendChild(frag)}
function closeSheet(cancelBattle=true){if(cancelBattle&&battle?.active){clearInterval(battle.timer);battle.active=false;battle=null;toast('夜番を中断しました。','warn')}els.modal.innerHTML=''}
function section(title,right,body){return`<section class="section"><h3 class="sectionTitle"><span>${title}</span><span>${right||''}</span></h3>${body}</section>`}
function specializationHtml(){return`<div class="choiceGrid"><button class="card choice" style="--choice:#ef8c5a" data-action="specialize" data-style="street"><i>≈</i><h3>にぎやかな屋台型</h3><p>客数が多く、魚を素早く販売。夜番では高速連射。</p><b>短い周期・低単価</b></button><button class="card choice" style="--choice:#d7b064" data-action="specialize" data-style="bistro"><i>◌</i><h3>静かな小料理屋型</h3><p>少ない客へ丁寧に提供。夜番では一発が重い。</p><b>長い周期・高単価</b></button></div>`}
function openFood(){const styleName=state.specialization==='street'?'にぎやかな屋台型':state.specialization==='bistro'?'静かな小料理屋型':'まだ決めていません';openSheet('さかな食堂','3F · MUGI’S LITTLE KITCHEN',`<div class="sceneHero"><img src="${ART.food}" alt="ムギが働くさかな食堂"><div class="sceneHeroCopy"><small>THE FIRST SHOP</small><h3>ムギの夢が、店の形になる。</h3><p>営業は自動。プレイヤーは店の方向と、ここぞという準備を決めます。</p></div></div>${section('店の状態','',`<div class="stats"><div class="stat"><small>在庫</small><strong>${state.stock}/12</strong><p>なくなると自動営業が停止</p></div><div class="stat"><small>累計販売</small><strong>${fmt(state.sales)}皿</strong><p>1皿 ${salePrice()}コイン</p></div><div class="stat"><small>店の方向</small><strong>${styleName}</strong><p>暮らし・売上・夜番が変化</p></div><div class="stat"><small>自動仕入れ</small><strong>${state.autoOrder?'ON':'OFF'}</strong><p>在庫2以下で作動</p></div></div>`)}${section('短い手作業','魚を棚へ',`<div class="card fishTask"><h3>皿を右の棚まで滑らせる</h3><p>毎回の販売は自動です。手で準備するのは、強化したい時だけ。</p><div class="fishLane"><span id="fishPlate" class="fishPlate"></span><input id="fishRange" class="fishRange" type="range" min="0" max="100" value="0" aria-label="魚の皿を棚へ滑らせる"></div><div class="actions"><button class="button ghost" data-action="auto-order">自動仕入れ ${state.autoOrder?'ON':'OFF'}</button><button class="button lime" data-action="quick-prep">魚を並べる · 8¢</button></div></div>`)}${!state.specialization?section('店の進む方向','最初の重要な選択',specializationHtml()):''}`);bindFishRange()}
function bindFishRange(){const range=$('#fishRange'),plate=$('#fishPlate');if(!range||!plate)return;const move=()=>{const lane=range.parentElement,max=Math.max(0,lane.clientWidth-110);plate.style.setProperty('--fishX',`${max*(+range.value/100)}px`)};range.addEventListener('input',move);range.addEventListener('change',()=>{if(+range.value>=88)prepareFish();else{range.value=0;move()}});move()}
function prepareFish(){if(state.stock>=12)return toast('棚はもういっぱいです。');if(state.coins<8)return toast('8コイン必要です。','warn');state.coins-=8;state.stock=clamp(state.stock+4,0,12);state.mugiMood=clamp(state.mugiMood+2,0,100);addMemory('first-prep');save();toast('ムギと魚を棚へ並べました。','good');openFood();render(true)}
function specialize(style){if(state.specialization||!['street','bistro'].includes(style))return;state.specialization=style;state.mugiMood=clamp(state.mugiMood+5,0,100);save();toast(style==='street'?'にぎやかな屋台型に決めました。':'静かな小料理屋型に決めました。','good');openFood();render(true)}
function openHome(){openSheet('猫の共同部屋','2F · A HOME BEFORE A WORKPLACE',`<div class="sceneHero"><img src="${ART.home}" alt="共同部屋で休むムギ"><div class="sceneHeroCopy"><small>MUGI IS HOME</small><h3>${state.mugiMood<55?'今日は少し疲れている。':'ムギは安心して丸くなっている。'}</h3><p>店の効率より先に、猫の暮らしを見る場所です。</p></div></div>${section('今日のムギ','',`<div class="stats"><div class="stat"><small>ごきげん</small><strong>${Math.round(state.mugiMood)}%</strong><p>${state.mugiMood>=75?'尻尾がよく動いています':state.mugiMood>=50?'少し休みたそうです':'今日は仕事を減らした方がよさそう'}</p></div><div class="stat"><small>好きなもの</small><strong>焼きさかな</strong><p>箱より先に魚を見つける</p></div><div class="stat"><small>今の役割</small><strong>店主見習い</strong><p>3F・さかな食堂</p></div><div class="stat"><small>関係</small><strong>最初の家族</strong><p>この塔へ最初に来た猫</p></div></div>`)}<div class="actions"><button class="button lime" data-action="pet">ムギをなでる</button><button class="button" data-action="rest">一緒に休む</button></div>`)}
function petMugi(){if(now()-state.lastPet<20000)return toast('ムギはまだ満足そうです。');state.lastPet=now();state.mugiMood=clamp(state.mugiMood+6,0,100);save();toast('ムギが目を細めました。','good');openHome();render(true)}
function restMugi(){if(now()-state.lastRest<45000)return toast('さっき休んだばかりです。');state.lastRest=now();state.mugiMood=clamp(state.mugiMood+14,0,100);addMemory('first-home');save();toast('静かな時間を一緒に過ごしました。','good');openHome();render(true)}
function openLobby(){const ready=state.sales>=2&&state.stock>=2;openSheet('タワーロビー','1F · NIGHT SHIFT ENTRANCE',`<div class="sceneHero"><img src="${ART.lobby}" alt="夜のタワーロビー"><div class="sceneHeroCopy"><small>C.L.E.A.N. AUTOMATED INSPECTION</small><h3>${state.firstNightDone?'ここは、もう空き家ではない。':'市の清掃機が、この塔を無人だと誤認している。'}</h3><p>昼の商品が、夜には猫たちの家を守る手段になります。</p></div></div>${section('今夜の条件','',`<div class="stats"><div class="stat"><small>必要販売</small><strong>${Math.min(state.sales,2)}/2</strong><p>店が動いている証明</p></div><div class="stat"><small>魚の在庫</small><strong>${state.stock}/2</strong><p>通常攻撃に使用</p></div></div>`)}<div class="actions"><button class="button ${ready?'warm':'ghost'}" data-action="start-night" ${ready?'':'disabled'}>${state.firstNightDone?'夜番をもう一度試す':'最初の夜番を始める'}</button></div>${!ready?`<div class="info" style="margin-top:12px">先にさかな食堂で2皿以上販売し、魚を2個以上残してください。</div>`:''}`)}
function openRoof(){overview=true;els.world.classList.add('overview');els.overview.querySelector('small').textContent='通常';closeSheet();els.scroll.scrollTo({top:0,behavior:'smooth'})}
function catsSheet(){const cards=Object.entries(CATS).map(([id,c],i)=>`<article class="card catCard ${i?'locked':''}"><img src="${c.art}" alt="${c.name}" draggable="false"><div><h3>${c.name}</h3><p>${c.role}<br>${c.trait}</p><span>${i?'訪問予定':'現在の住人'}</span></div></article>`).join('');openSheet('猫たち','RESIDENTS & FUTURE VISITORS',`<div class="info">住人猫は深い物語と生活動作を持ち、訪問猫は塔へ収集の広がりを作ります。V0.8ではムギの縦型スライスを完成させます。</div>${section('住人と訪問予定','1 / 4',`<div class="catList">${cards}</div>`)}`)}
function buildSheet(){openSheet('塔を育てる','REPAIR & SPECIALIZE',`${section('さかな食堂','暮らし・売上・夜番を同時に変える',state.specialization?`<div class="card" style="padding:16px"><h3 style="margin:0 0 6px">${state.specialization==='street'?'にぎやかな屋台型':'静かな小料理屋型'}</h3><p style="margin:0;color:#fff8;font-size:9px;line-height:1.6">単純な「売上＋10%」ではなく、見た目・営業周期・夜番の攻撃方法が変わります。</p></div>`:specializationHtml())}${section('次の復旧候補','V0.9',`<div class="choiceGrid"><article class="card choice"><i style="--choice:#72b8a0">◎</i><h3>毛糸クラブ</h3><p>訪問猫が増える遊び場。夜は毛糸で清掃機を遅くする。</p><b>次のVertical Slice</b></article><article class="card choice"><i style="--choice:#a996eb">✦</i><h3>肉球サロン</h3><p>猫の疲労を整える。夜は泡で装甲を弱める。</p><b>設計枠を確保</b></article></div>`)}`)}
function memoriesSheet(){state.memoryNew=false;save();els.memoryBadge.classList.add('hidden');const data=[['arrival','塔へ来た夜','ムギが最初の窓からこちらを見た。',ART.title],['first-prep','最初の仕込み','一緒に魚を棚へ並べた。',ART.food],['first-home','ここが家になる','仕事を忘れて、一緒に休んだ。',ART.memory],['first-night','空き家ではない','C.L.E.A.N.へ猫たちの暮らしを示した。',ART.foodNight]],cards=data.map(([id,title,text,art])=>{const unlocked=state.memories.includes(id);return`<article class="card memoryCard ${unlocked?'':'locked'}"><img src="${art}" alt=""><div><small>${unlocked?'MEMORY':'LOCKED MEMORY'}</small><h3>${unlocked?title:'まだ起きていない出来事'}</h3>${unlocked?`<p style="margin:4px 0 0;color:#fff8;font-size:8px">${text}</p>`:''}</div></article>`}).join('');openSheet('思い出帳','LIFE INSIDE THE TOWER',`<div class="info">数値の達成だけでなく、猫と塔で起きた短い出来事を残します。</div>${section('ムギとの記録',`${state.memories.length}/4`,`<div class="memoryGrid">${cards}</div>`)}`)}
function menuSheet(){openSheet('設定','CAT’S TOWER · V0.8',`<div class="card" style="padding:15px"><h3 style="margin:0 0 6px">Living Tower Vertical Slice</h3><p style="margin:0;color:#fff8;font-size:9px;line-height:1.65">ムギ、さかな食堂、共同部屋、最初の夜番を、本番方向の最小完成単位として実装しています。</p></div><div class="actions"><button class="button ghost" data-action="toggle-sound">効果音 ${state.sound?'ON':'OFF'}</button><button class="button warm" data-action="reset-confirm">最初から</button></div>`)}
function resetConfirm(){openSheet('最初からやり直す','RESET V0.8 SAVE',`<div class="battleResult"><i>!</i><h3>進行をすべて消します</h3><p>コイン、思い出、店の方向、夜番の記録は元に戻せません。</p></div><div class="actions"><button class="button ghost" data-close="1">戻る</button><button class="button warm" data-action="reset">初期化する</button></div>`)}
function coinSheet(){openSheet('タワーのコイン','AUTOMATED ECONOMY',`<div class="stats"><div class="stat"><small>所持金</small><strong>${fmt(state.coins)}¢</strong><p>店の復旧と準備に使用</p></div><div class="stat"><small>通常販売</small><strong>${salePrice()}¢</strong><p>${Math.round(saleInterval()/100)/10}秒ごと</p></div><div class="stat"><small>救済</small><strong>最大35¢</strong><p>完全停止時だけロビーのチップ箱に蓄積</p></div><div class="stat"><small>強制広告</small><strong>なし</strong><p>コア体験を止めない</p></div></div>`)}
function startNight(){if(state.sales<2||state.stock<2)return toast('まだ夜番の準備ができていません。','warn');closeSheet(false);state.nightAttempts++;battle={active:true,hp:state.firstNightDone?105:82,max:state.firstNightDone?105:82,progress:0,stunUntil:0,lastShot:0,bellUsed:false,boxUsed:false,timer:0};openSheet('最初の夜番','C.L.E.A.N. INSPECTION',`<div class="battleCard"><img class="battleBg" src="${ART.foodNight}" alt="夜のさかな食堂"><div class="battleTint"></div><div class="battleHud"><header><small>AUTOMATED CLEANING UNIT</small><h3>店を「廃棄物」から守る</h3><div class="enemyBar"><i id="enemyHp" style="width:100%"></i></div></header></div><div class="enemyProgress"><small><span>1F 入口</span><span id="enemyProgressLabel">屋上まで 100%</span></small><div class="progressTrack"><i id="enemyProgress" style="width:0%"></i></div></div><div class="battleTools"><button data-action="battle-fish"><i>≈</i><b>魚を投げる</b><small>在庫1・14ダメージ</small></button><button data-action="battle-bell"><i>♢</i><b>ベルを鳴らす</b><small>3秒停止・1回</small></button><button data-action="battle-box"><i>□</i><b>箱で止める</b><small>22ダメージ・1回</small></button></div></div>`);battle.timer=setInterval(battleTick,200);battleTick()}
function battleDamage(n){if(!battle?.active)return;battle.hp=Math.max(0,battle.hp-n);if(battle.hp<=0)finishNight(true)}
function battleTick(){if(!battle?.active)return;const t=now(),dt=.2;if(t>=battle.stunUntil)battle.progress+=100/34*dt;const attackEvery=state.specialization==='street'?1050:state.specialization==='bistro'?1750:1350,damage=state.specialization==='bistro'?11:state.specialization==='street'?6:8;if(state.stock>0&&t-battle.lastShot>=attackEvery){battle.lastShot=t;state.stock--;battleDamage(damage)}const hp=$('#enemyHp'),pg=$('#enemyProgress'),label=$('#enemyProgressLabel');if(hp)hp.style.width=`${battle.hp/battle.max*100}%`;if(pg)pg.style.width=`${clamp(battle.progress,0,100)}%`;if(label)label.textContent=`屋上まで ${Math.max(0,Math.ceil(100-battle.progress))}%`;if(battle.progress>=100)finishNight(false)}
function battleTool(type){if(!battle?.active)return;if(type==='fish'){if(state.stock<1)return toast('魚の在庫がありません。','warn');state.stock--;battleDamage(14);toast('ムギが魚を投げました。')}if(type==='bell'){if(battle.bellUsed)return toast('ベルはもう使いました。');battle.bellUsed=true;battle.stunUntil=now()+3000;toast('清掃機が音を確認しています。','good');const b=$('[data-action="battle-bell"]');if(b)b.disabled=true}if(type==='box'){if(battle.boxUsed)return toast('箱はもう使いました。');battle.boxUsed=true;battleDamage(22);toast('入口を箱で塞ぎました。','good');const b=$('[data-action="battle-box"]');if(b)b.disabled=true}}
function finishNight(win){if(!battle?.active)return;clearInterval(battle.timer);battle.active=false;battle=null;if(win){state.firstNightDone=true;state.coins+=68;state.mugiMood=clamp(state.mugiMood+10,0,100);addMemory('first-night');save();render(true);openSheet('夜番を終えました','THE TOWER IS NOT EMPTY',`<div class="battleResult"><i>✓</i><h3>ここは、猫たちが暮らす家です。</h3><p>C.L.E.A.N.は一時的に撤退しました。昼の店と商品が、そのまま夜の解決方法になりました。</p></div><div class="stats"><div class="stat"><small>報酬</small><strong>+68¢</strong><p>次の復旧に使用</p></div><div class="stat"><small>思い出</small><strong>1枚</strong><p>思い出帳へ追加</p></div></div><div class="actions"><button class="button lime" data-close="1">タワーへ戻る</button></div>`)}else{state.mugiMood=clamp(state.mugiMood-3,0,100);save();render(true);openSheet('今夜は撤退','NIGHT SHIFT REPORT',`<div class="battleResult"><i style="background:linear-gradient(#ffb28b,#ef7953);color:#401d13">!</i><h3>失うものはありません。</h3><p>猫や店舗は消えません。魚を準備し、使う道具の順番を変えて再挑戦できます。</p></div><div class="actions"><button class="button ghost" data-close="1">タワーへ戻る</button><button class="button warm" data-action="start-night">再挑戦</button></div>`)}}
function runContext(){const a=els.context.dataset.action;if(a==='food')openFood();else if(a==='home')openHome();else if(a==='lobby')openLobby();else buildSheet()}function openRoom(type){if(type==='food')openFood();else if(type==='home')openHome();else if(type==='lobby')openLobby();else openRoof()}function navTo(name){els.nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));if(name==='tower')closeSheet();else if(name==='cats')catsSheet();else if(name==='build')buildSheet();else memoriesSheet()}
function tick(){const t=now();let changed=false;if(state.orderEnds&&state.orderEnds<=t){state.orderEnds=0;state.stock=clamp(state.stock+6,0,12);toast('魚が届きました。ムギが棚を確認しています。','good');changed=true}if(!battle?.active&&state.stock>0&&t>=state.lastSale){state.stock--;state.sales++;state.coins+=salePrice();state.mugiMood=clamp(state.mugiMood-.35,0,100);state.lastSale=t+saleInterval();changed=true}if(!state.orderEnds&&state.autoOrder&&state.stock<=2&&state.coins>=orderCost()){state.coins-=orderCost();state.orderEnds=t+5000;toast('ムギが次の魚を仕入れました。');changed=true}if(!state.stock&&!state.orderEnds&&state.coins<35&&t-state.lastSupport>=1000){const n=Math.floor((t-state.lastSupport)/1000);state.coins=Math.min(35,state.coins+n);state.lastSupport+=n*1000;changed=true}if(changed){save();render(true)}else{updateHeader();updateContext()}}
function startGame(){if(!els.game.classList.contains('hidden'))return;state.hasPlayed=true;save();els.splash.animate([{opacity:1},{opacity:0}],{duration:420,fill:'forwards'}).finished.finally(()=>els.splash.classList.add('hidden'));els.game.classList.remove('hidden');render(false);requestAnimationFrame(()=>{const food=els.tower.querySelector('[data-room="food"]');if(food)els.scroll.scrollTop=Math.max(0,food.offsetTop-110)});clearInterval(timer);timer=setInterval(tick,500);if(offline?.sold)toast(`留守中に焼きさかなが${offline.sold}皿売れました。`,'good')}
function modalClick(e){const close=e.target.closest('[data-close]');if(close){if(e.target===close||close.tagName==='BUTTON')closeSheet();return}const a=e.target.closest('[data-action]');if(!a)return;const type=a.dataset.action;if(type==='specialize')specialize(a.dataset.style);else if(type==='quick-prep')prepareFish();else if(type==='auto-order'){state.autoOrder=!state.autoOrder;save();openFood();render(true)}else if(type==='pet')petMugi();else if(type==='rest')restMugi();else if(type==='start-night')startNight();else if(type==='battle-fish')battleTool('fish');else if(type==='battle-bell')battleTool('bell');else if(type==='battle-box')battleTool('box');else if(type==='toggle-sound'){state.sound=!state.sound;save();menuSheet()}else if(type==='reset-confirm')resetConfirm();else if(type==='reset'){localStorage.removeItem(KEY);state=fresh();closeSheet(false);render(false);toast('V0.8を最初から開始しました。','good')}}
function towerClick(e){const a=e.target.closest('[data-action="open-room"]');if(a)return openRoom(a.dataset.room);const f=e.target.closest('[data-room]');if(f)openRoom(f.dataset.room)}function toggleOverview(){overview=!overview;els.world.classList.toggle('overview',overview);els.overview.querySelector('small').textContent=overview?'通常':'全体';if(overview)els.scroll.scrollTo({top:0,behavior:'smooth'})}
els.start.addEventListener('click',startGame);els.context.addEventListener('click',runContext);els.tower.addEventListener('click',towerClick);els.nav.addEventListener('click',e=>{const b=e.target.closest('[data-nav]');if(b)navTo(b.dataset.nav)});els.overview.addEventListener('click',toggleOverview);els.modal.addEventListener('click',modalClick);els.menu.addEventListener('click',menuSheet);els.coin.addEventListener('click',coinSheet);els.brand.addEventListener('click',()=>openSheet("Cat's tower",'LIVING TOWER CONCEPT',`<div class="info">昼は小さな猫たちの店。夜はみんなで守る家。猫の行動を観察し、短い判断で古い塔を本当の居場所へ変えていきます。</div>`));addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save()});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js?v=080').catch(()=>{}));
updateHeader();updateContext();if(state.hasPlayed)els.start.textContent='タワーへ戻る';window.__CATS_TEST_API__={version:VERSION,getState:()=>structuredClone(state),reset:()=>{localStorage.removeItem(KEY);state=fresh();render(false)},unlock:()=>{state.specialization='street';state.stock=10;state.sales=8;state.coins=800;state.memories=['arrival','first-prep','first-home','first-night'];state.firstNightDone=true;save();render(false)},startNight};
})();
