(function attachCatsTowerData(root) {
  'use strict';

  const VERSION = '0.8.2';
  const BUILD = 'v082-pixel-tower-gameplay-redesign';
  const GAMEPLAY_SCHEMA = 2;

  const BALANCE = Object.freeze({
    fixedStepMs: 100,
    maxAdvanceMs: 60 * 60 * 1000,
    offlineCapMs: 8 * 60 * 60 * 1000,
    // Keep the battlefield readable. Named cats unlock into reserved party slots,
    // so the live capacity grows 4 -> 5 -> 6 rather than filling all six slots
    // with helpers before Luna and Toto can arrive.
    unitCap: 6,
    startingPartyCap: 4,
    helperVariantCount: 3,
    startingCoins: 72,
    startingFish: 4,
    autoDispatchBaseMs: 2300,
    autoDispatchMinimumMs: 650,
    autoDispatchLevelFactor: 0.89,
    manualDispatchCooldownMs: 150,
    unitTravelBaseMs: 1150,
    unitAttackIntervalMs: 900,
    enemyAttackIntervalMs: 1250,
    floorVictoryHoldMs: 650,
    floorAscentMs: 1350,
    floorTransitionMs: 2000,
    wallFloor: 8,
    wallObserveMs: 10000,
    wallHpMultiplier: 6.5,
    dawnUnlockFloor: 8,
    restaurantUnlockFloor: 3,
    roomUnlockFloor: 5,
    firstBossFloor: 10,
    rallyDurationMs: 6000,
    rallyCooldownMs: 14000,
    rallyAttackSpeedFactor: 0.72,
    rallyTravelSpeedFactor: 0.78,
    restaurantDeliveryBaseMs: 11000,
    restaurantDeliveryMinimumMs: 6500,
    restaurantDeliveryLevelFactor: 0.94,
    restaurantBuffDurationMs: 4000,
    restaurantAttackSpeedFactor: 0.82,
    restaurantDeliveryCoinBase: 3,
    roomRecoveryBaseMs: 9000,
    roomUnlockedRecoveryFactor: 0.7,
    roomRecoveryLevelFactor: 0.87,
    roomRecoveryMinimumMs: 2400,
    baseCatAttack: 5.2,
    baseCatHp: 24,
    helperAttackFactor: 0.72,
    helperHpFactor: 0.8,
    mugiAttackLevelFactor: 1.25,
    mugiHpLevelFactor: 1.2,
    weaponLevelFactor: 1.34,
    restaurantAttackPerLevel: 0.07,
    restaurantIncomePerLevel: 0.12,
    roomPowerPerLevel: 0.1,
    permanentPowerPerShard: 0.55,
    enemyBaseHp: 21,
    enemyHpFloorFactor: 1.82,
    enemyBaseAttack: 3.2,
    enemyAttackFloorFactor: 1.29,
    enemyMiniBossMultiplier: 2.1,
    enemyBossMultiplier: 3.4,
    enemyWallRegenPerSecond: 0.0035,
    baseKillReward: 9,
    killRewardFloorFactor: 1.42,
    firstNightRewardCoins: 120,
  });

  const ART = Object.freeze({
    title: '/assets/v080/pixel-r2/tower-night-r2.png',
    tower: '/assets/v080/pixel-r2/tower-night-r2.png',
    mugiSprites: '/assets/v080/pixel-r2/mugi-sprites-r2.png',
    crowSprites: '/assets/v080/pixel-r2/crow-sprites-r2.png',
    castSprites: '/assets/v082/pixel-r3/cats-cast-r3.png',
    enemySprites: '/assets/v082/pixel-r3/enemies-r3.png',
  });

  const CATS = Object.freeze({
    mugi: Object.freeze({
      id: 'mugi',
      name: 'ムギ',
      role: 'frontline',
      named: true,
      unlockFloor: 1,
      attackFactor: 1,
      hpFactor: 1.18,
      travelFactor: 1,
      attackIntervalFactor: 1,
      appearance: 'ginger',
    }),
    luna: Object.freeze({
      id: 'luna',
      name: 'ルナ',
      role: 'ranged',
      named: true,
      unlockFloor: 2,
      attackFactor: 0.86,
      hpFactor: 0.72,
      travelFactor: 0.76,
      attackIntervalFactor: 0.84,
      appearance: 'moon-gray',
    }),
    toto: Object.freeze({
      id: 'toto',
      name: 'トト',
      role: 'support',
      named: true,
      unlockFloor: 5,
      attackFactor: 0.46,
      hpFactor: 0.88,
      travelFactor: 0.9,
      attackIntervalFactor: 1.28,
      appearance: 'cream',
      supportHealFactor: 0.035,
      supportCooldownReductionMs: 90,
    }),
    'helper-tabby': Object.freeze({
      id: 'helper-tabby',
      name: 'キジトラ',
      role: 'frontline',
      named: false,
      unlockFloor: 1,
      attackFactor: 0.7,
      hpFactor: 0.86,
      travelFactor: 1.04,
      attackIntervalFactor: 1.02,
      appearance: 'tabby',
    }),
    'helper-gray': Object.freeze({
      id: 'helper-gray',
      name: '灰ねこ',
      role: 'ranged',
      named: false,
      unlockFloor: 1,
      attackFactor: 0.62,
      hpFactor: 0.66,
      travelFactor: 0.83,
      attackIntervalFactor: 0.9,
      appearance: 'gray',
    }),
    'helper-calico': Object.freeze({
      id: 'helper-calico',
      name: '三毛ねこ',
      role: 'support',
      named: false,
      unlockFloor: 1,
      attackFactor: 0.52,
      hpFactor: 0.74,
      travelFactor: 0.94,
      attackIntervalFactor: 1.12,
      appearance: 'calico',
      supportHealFactor: 0.018,
      supportCooldownReductionMs: 45,
    }),
  });

  const NAMED_CAT_ORDER = Object.freeze(['mugi', 'luna', 'toto']);
  const HELPER_ROTATION = Object.freeze(['helper-tabby', 'helper-gray', 'helper-calico']);

  const ENEMIES = Object.freeze({
    crow: Object.freeze({
      id: 'crow',
      name: '夜ガラス',
      kind: 'normal',
      hpMultiplier: 1,
      attackMultiplier: 1,
      rewardMultiplier: 1,
    }),
    owl: Object.freeze({
      id: 'owl',
      name: '夜フクロウ',
      kind: 'normal',
      hpMultiplier: 1.12,
      attackMultiplier: 0.82,
      attackIntervalMultiplier: 0.78,
      rewardMultiplier: 1.08,
    }),
    barrier: Object.freeze({
      id: 'black-feather-barrier',
      name: '黒羽の結界',
      kind: 'wall',
      hpMultiplier: 1,
      attackMultiplier: 0.76,
      attackIntervalMultiplier: 1.18,
      rewardMultiplier: 1.35,
    }),
    boss: Object.freeze({
      id: 'great-crow',
      name: 'クロバネ',
      kind: 'boss',
      hpMultiplier: 1,
      attackMultiplier: 1.16,
      attackIntervalMultiplier: 0.92,
      rewardMultiplier: 1.55,
      art: ART.enemySprites,
    }),
  });

  const ENEMY_ROTATION = Object.freeze(['crow', 'owl']);

  const FLOOR_NODES = Object.freeze({
    restaurant: Object.freeze({
      id: 'restaurant',
      floor: BALANCE.restaurantUnlockFloor,
      name: 'さかな食堂',
      description: '制圧した階から、攻撃とコイン獲得を支援する。',
    }),
    room: Object.freeze({
      id: 'room',
      floor: BALANCE.roomUnlockFloor,
      name: '猫の共同部屋',
      description: '夜明けを越えて残る、猫たちの恒久強化拠点。',
    }),
  });

  const UPGRADES = Object.freeze({
    mugi: Object.freeze({
      id: 'mugi',
      stateField: 'mugiLevel',
      name: 'ムギの特訓',
      currency: 'coins',
      baseCost: 34,
      costFactor: 1.52,
      minimumLevel: 1,
    }),
    weapon: Object.freeze({
      id: 'weapon',
      stateField: 'weaponLevel',
      name: '猫パンチ',
      currency: 'coins',
      baseCost: 45,
      costFactor: 1.57,
      minimumLevel: 1,
    }),
    dispatch: Object.freeze({
      id: 'dispatch',
      stateField: 'dispatchLevel',
      name: '出撃口',
      currency: 'coins',
      baseCost: 58,
      costFactor: 1.62,
      minimumLevel: 1,
    }),
    restaurant: Object.freeze({
      id: 'restaurant',
      stateField: 'restaurantLevel',
      name: 'さかな食堂',
      currency: 'coins',
      baseCost: 76,
      costFactor: 1.68,
      minimumLevel: 1,
      unlockFloor: BALANCE.restaurantUnlockFloor,
    }),
    room: Object.freeze({
      id: 'room',
      stateField: 'roomLevel',
      name: '共同部屋',
      currency: 'dawnShards',
      baseCost: 1,
      costFactor: 1.85,
      minimumLevel: 1,
      unlockFloor: BALANCE.roomUnlockFloor,
      permanent: true,
    }),
  });

  root.CatsTowerData = Object.freeze({
    VERSION,
    BUILD,
    GAMEPLAY_SCHEMA,
    SAVE_KEY: 'cats-tower-v080',
    LEGACY_KEY: 'cats-tower-v01',
    SCHEMA1_BACKUP_KEY: 'cats-tower-v080-schema1-backup',
    BALANCE,
    ART,
    CATS,
    NAMED_CAT_ORDER,
    HELPER_ROTATION,
    ENEMIES,
    ENEMY_ROTATION,
    FLOOR_NODES,
    UPGRADES,
  });
})(typeof window !== 'undefined' ? window : globalThis);
